print("Enter two complex numbers in the form a+bj:")
n1 = complex(input())
n2 = complex(input())
print("sum =", n1 + n2)
print("Enter two complex numbers in the form a+bj:")
n1 = complex(input())
n2 = complex(input())
print("sub =", n1 - n2)
print("Enter two complex numbers in the form a+bj:")
n1 = complex(input())
n2 = complex(input())
print("mul =", n1 * n2)